In [2]:
import tensorflow as tf
import pathlib
import os
import shutil
import numpy as np

In [2]:
data_dir = pathlib.Path('imgs2/test/')
image_count = len(list(data_dir.glob('*/*.jpg')))
print(image_count)

733


In [3]:
batch_size = 32
img_height = 224
img_width = 224
os.listdir("imgs2/test/")

['Apple', 'Banana', 'Tomato', 'Watermelon']

In [4]:
train_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="training",
  label_mode='categorical',
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

Found 733 files belonging to 4 classes.
Using 587 files for training.


In [5]:
val_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="validation",
  label_mode='categorical',
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

Found 733 files belonging to 4 classes.
Using 146 files for validation.


In [6]:
class_names = train_ds.class_names
print(class_names)

['Apple', 'Banana', 'Tomato', 'Watermelon']


In [7]:
num_classes = 4

In [8]:
model = tf.keras.Sequential([
  tf.keras.layers.Rescaling(1./255),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(num_classes,activation = "softmax")
])

In [9]:
model.compile(
  optimizer='adam',
  loss=tf.keras.losses.CategoricalCrossentropy(),
  metrics=['accuracy'])


In [10]:
model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=9
)

Epoch 1/9
19/19 [==============================] - 11s 573ms/step - loss: 0.5512 - accuracy: 0.8228 - val_loss: 0.0062 - val_accuracy: 1.0000
Epoch 2/9
19/19 [==============================] - 11s 585ms/step - loss: 9.1314e-04 - accuracy: 1.0000 - val_loss: 2.5207e-04 - val_accuracy: 1.0000
Epoch 3/9
19/19 [==============================] - 11s 585ms/step - loss: 6.5528e-05 - accuracy: 1.0000 - val_loss: 7.7157e-07 - val_accuracy: 1.0000
Epoch 4/9
19/19 [==============================] - 11s 579ms/step - loss: 1.6497e-05 - accuracy: 1.0000 - val_loss: 3.1354e-07 - val_accuracy: 1.0000
Epoch 5/9
19/19 [==============================] - 11s 598ms/step - loss: 1.0083e-06 - accuracy: 1.0000 - val_loss: 9.3978e-07 - val_accuracy: 1.0000
Epoch 6/9
19/19 [==============================] - 11s 589ms/step - loss: 1.2538e-06 - accuracy: 1.0000 - val_loss: 7.9036e-07 - val_accuracy: 1.0000
Epoch 7/9
19/19 [==============================] - 11s 596ms/step - loss: 9.7397e-07 - accuracy: 1.0000 - va

In [11]:
model.save('model.h5')

In [3]:
img_height = 224
img_width = 224
model = tf.keras.models.load_model('model.h5')
class_names = ['Apple', 'Banana', 'Tomato', 'Watermelon']

In [5]:
tomate_path = 'tomate.jpg'
img = tf.keras.utils.load_img(
    tomate_path, target_size=(img_height, img_width)
)
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) 
predictions = model.predict(img_array)
print(predictions)

print(
    "La imagen es un/a {} con un {:.2f} porciento de confianza."
    .format(class_names[np.argmax(predictions)], 100 * np.max(predictions))
)

1/1 [==============================] - 0s 19ms/step
[[4.2113775e-04 1.5086234e-02 9.8449266e-01 8.2511781e-10]]
La imagen es un/a Tomato con un 98.45 porciento de confianza.


In [6]:
platano_path = 'platano.jpg'
img = tf.keras.utils.load_img(
    platano_path, target_size=(img_height, img_width)
)
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch

predictions = model.predict(img_array)
print(predictions)

print(
    "La imagen es un/a {} con un {:.2f} porciento de confianza."
    .format(class_names[np.argmax(predictions)], 100 * np.max(predictions))
)

1/1 [==============================] - 0s 22ms/step
[[6.5699567e-07 9.9999869e-01 2.2927443e-21 5.5141851e-07]]
La imagen es un/a Banana con un 100.00 porciento de confianza.


In [7]:
apple_path = 'manzanas.jpg'
img = tf.keras.utils.load_img(
    apple_path, target_size=(img_height, img_width)
)
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch

predictions = model.predict(img_array)
print(predictions)

print(
    "La imagen es un/a {} con un {:.2f} porciento de confianza."
    .format(class_names[np.argmax(predictions)], 100 * np.max(predictions))
)

1/1 [==============================] - 0s 20ms/step
[[9.8426855e-01 1.5731040e-02 1.3315485e-10 4.1940135e-07]]
La imagen es un/a Apple con un 98.43 porciento de confianza.


In [14]:
watermelon_path = 'watermelon.jpg'
img = tf.keras.utils.load_img(
    watermelon_path, target_size=(img_height, img_width)
)
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch

predictions = model.predict(img_array)
print(predictions)

print(
    "La imagen es un/a {} con un {:.2f} porciento de confianza."
    .format(class_names[np.argmax(predictions)], 100 * np.max(predictions))
)

1/1 [==============================] - 0s 22ms/step
[[5.1081568e-01 2.8283853e-02 1.6886135e-07 4.6090031e-01]]
La imagen es un/a Watermelon con un 51.08 porciento de confianza.
